### ISSUE TITLE
devel:kubic GPG signing key expired

### ISSUE THREAD

**Issue by miminar** [kubic-project/kubic-o-o#46]
I hope this is the right place.

We're hitting this in our build pipeline:

```
W: GPG error: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/xUbuntu_22.04  InRelease: The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/xUbuntu_22.04  InRelease' is not signed.
W: GPG error: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04  InRelease: The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
```

Due to the key being expired:

```
pub   rsa2048/0x4D64390375060AA4 2018-08-03 [SC] [expired: 2022-12-06]
      Key fingerprint = 2472 D6D0 D2F6 6AF8 7ABA  8DA3 4D64 3903 7506 0AA4
uid                   [ expired] devel:kubic OBS Project <devel:kubic@build.opensuse.org>
```

Could you please extend?

**Comment by miminar** [comment]
It looks to fixed now. Thank you! :tada:

**Comment by Vasu-Mekala** [comment]
I am getting the same error can't upgrade from 20.x to 22.x
Please help. thank you!

Err:7 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4D64390375060AA4
Reading package lists... Done
W: GPG error: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4D64390375060AA4
E: The repository 'http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by cz172638** [comment]
hi
again it expired 3 days ago,
we can't update 20.04 lts
can you please extend?

**Comment by sfc-gh-abhala** [comment]
I am facing the same problem
